### ISSUE TITLE
Different output when running benchmark.

### ISSUE THREAD

**Issue by benoittgt** [Borzik/ams-jbuilder-pg#1]
Hello Felix

First thanks for this awesome benchmark you gave us, it's very interesting.

I'm trying to run the test on my own machine without success. First I had problem with `test:prepare` : 

``` shell
$ rake test:benchmark
rake aborted!
Don't know how to build task 'test:prepare'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
-e:1:in `<main>'
Tasks: TOP => test:benchmark
(See full trace by running task with --trace)
```

Strange because db was create, migrate, seeded...

I've finally add `task 'test:prepare'` into my Rakefile and now I get :

``` shell
rake test:benchmark
Run options: --seed 64113

# Running:

IndexTest#test_posts_index (31 ms warmup)
           wall_time: 2 ms
              memory: unsupported
        process_time: 2 ms
.

Finished in 0.457237s, 2.1870 runs/s, 0.0000 assertions/s.
```

Very different result like you, process time seems fake. Did you make your benchmark in a different way ?

Thanks in advance.

**Comment by Borzik** [comment]
`rake db:test:prepare` is deprecated. Use `RAILS_ENV=test rake db:setup` if you want to create the DB, migrate and seed it, or `RAILS_ENV=test rake db:seed` to only seed it.
To validate your results, you can even run server under test environment and vists `/posts` path. It should render a JSON 1000 posts for you there.

**Comment by benoittgt** [comment]
Thanks Felix for the fast answer. 

With the setup and the seed it's far better: 

``` shell
rake test:profile                                                                                            [11:27:43]
Run options: --seed 48605

# Running:

IndexTest#test_posts_index (153 ms warmup)
           wall_time: 574 ms
              memory: 0 Bytes
        process_time: 1.10 sec
.

Finished in 11.756648s, 0.0851 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by Borzik** [comment]
As for

```
Completed 200 OK in 481ms (Views: 473.2ms | ActiveRecord: 5.9ms)
```

text, it's to be taken from `test.log` file (I didn't find a way to put that information right to test return, although I'd like to find a way to do that). So I've just taken a result close to an average from the log.

**Comment by benoittgt** [comment]
Thanks Felix.
